export const mockProposals = [
  {
    id: 1,
    title: "Should percent diversify the treasury?",
    description: "Diversify treasury holdings by allocating 20% to stable assets to reduce volatility and ensure long-term sustainability of the protocol.",
    status: "Pending",
    passPrice: 0.652,
    failPrice: 0.348,
    volume24h: 45230,
    endsAt: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000),
  },
  {
    id: 2,
    title: "Should percent reduce protocol fees?",
    description: "Reduce protocol fees from 0.3% to 0.25% to increase competitiveness and attract more trading volume.",
    status: "Pending",
    passPrice: 0.423,
    failPrice: 0.577,
    volume24h: 32100,
    endsAt: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000),
  },
  {
    id: 3,
    title: "Should percent implement a token buyback program?",
    description: "Implement a quarterly buyback program using 50% of protocol revenues to support token value.",
    status: "Passed",
    passPrice: 0.812,
    failPrice: 0.188,
    volume24h: 78500,
    endsAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
  },
  {
    id: 4,
    title: "Should percent integrate cross-chain bridges?",
    description: "Deploy bridges to Ethereum and Polygon to expand protocol reach and increase liquidity.",
    status: "Pending",
    passPrice: 0.701,
    failPrice: 0.299,
    volume24h: 56300,
    endsAt: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
  },
  {
    id: 5,
    title: "Should percent create a community grants program?",
    description: "Allocate 1M tokens for developer grants to accelerate ecosystem growth and innovation.",
    status: "Failed",
    passPrice: 0.389,
    failPrice: 0.611,
    volume24h: 23400,
    endsAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
  },
  {
    id: 6,
    title: "Should percent increase staking rewards?",
    description: "Increase staking APY from 8% to 12% to incentivize long-term token holding.",
    status: "Pending",
    passPrice: 0.567,
    failPrice: 0.433,
    volume24h: 41200,
    endsAt: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000),
  },
];